# Window rule
windowrule= match:class ^(GTK Application)$, size 50% 70%
windowrule= match:class ^(GTK Application)$, center on
windowrule = match:fullscreen 1, border_size 0

# no gaps in fullscreen
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0

# assign workspace to application
# windowrule = workspace 2 silent, class:(firefox-developer-edition)
