source = ~/.config/hypr/config.d/option.conf
source = ~/.config/hypr/config.d/monitor.conf
source = ~/.config/hypr/config.d/env.conf
source = ~/.config/hypr/config.d/window-rule.conf
source = ~/.config/hypr/config.d/bind.conf
source = ~/.config/hypr/config.d/startup.conf

# NVIDIA-specific environment variables
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = __GL_GSYNC_ALLOWED,0
env = __GL_VRR_ALLOWED,0

# Cursor settings (incl. NVIDIA no_hardware_cursors) live in config.d/option.conf
